#!/usr/bin/env python3
"""A6 (2026-09-24): append seven Bucks County / north-Montgomery towns to
data/towns.json for scripts/build-town-pages.js. Idempotent (skips slugs
that already exist). Meta descriptions over 165 chars are reported, not
asserted; trim them in data/towns.json afterwards."""
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent
p = ROOT / 'data/towns.json'; d = json.loads(p.read_text())
have = {t['slug'] for t in d['towns']}
IMG = {"introImage": "/IMAGES/Custom-Kitchen-Ambler-Pa.webp", "introImageBath": "/IMAGES/Custom-Bathroom-Ambler-Pa.webp",
       "ogImageBath": "https://www.bbassociatesco.com/IMAGES/Custom-Bathroom-Ambler-Pa.webp"}
def hero(name): return {"heroImage": f"/portfolio/KITCHENS/{name}", "ogImage": f"https://www.bbassociatesco.com/portfolio/KITCHENS/{name}"}
HEROES = ["B&B - Prager-kitchen/A12EE3BF-FDEB-4F6A-ADD0-BB95FCFADB88.jpeg", "B&B - Beth Rubin-kitchen/153E1359-5284-48E5-9F68-B497880FF6F7.jpeg", "BB-OLaughlin-kitchen/06BCD805-17A2-4A11-B4B7-6215BA68270F.jpeg", "B&B - McBride Kitchen/03A7198B-DACB-43CA-87B1-1148DB3DEEC8.jpeg"]
K = ["rubin-kitchen","broderick-kitchen","bryn-michaels-kitchen","lee-kitchen","ferrie-kitchen","ganescu-kitchen","giedrycz-kitchen","hess-kitchen","hornig-kitchen","kohl-kitchen","larkin-kitchen","mcbride-kitchen","peterson-kitchen","olaughlin-kitchen","oleg-kitchen","prager-kitchen","slingsby-kitchen"]
B = ["barenbaum-bathroom","borgia-bathroom","bridlehall-bathroom","frank-bathroom","cruz-bathroom","emad-bathroom","garvey-bathroom","giedrycz-bathroom","guttridge-bathroom","hartka-bathroom","hershey-bathroom","kaarby-bathroom","lashannon-bathroom","levinson-bathroom","petev-bathroom","odonnell-bathroom","sharada-bathroom","goldberg-bathroom","vartanian-bathroom"]
def pf(i): return {"kitchen": [K[(i*3)%len(K)], K[(i*3+1)%len(K)], K[(i*3+2)%len(K)]], "bathroom": [B[(i*3)%len(B)], B[(i*3+1)%len(B)], B[(i*3+2)%len(B)]]}

T = []
T.append({**{"slug":"doylestown","urlSlug":"doylestown-pa","displayName":"Doylestown","county":"Bucks County","regionEyebrow":"Bucks County",
 "townships":["Doylestown Borough","Doylestown Township"],"neighborhoods":["Doylestown Borough","Doylestown Township","the historic district","Fonthill","Buckingham"],
 "heroTowns":"Doylestown Borough · Doylestown Township · Historic District · Buckingham","neighbors":["new-hope","chalfont","warrington"],
 "nearbyGeneral":[{"label":"Doylestown & New Hope","href":"/service-areas/doylestown-new-hope-kitchen-remodeling/"},{"label":"Buckingham","href":"/service-areas/buckingham-pa-remodeling/"},{"label":"Chalfont","href":"/service-areas/chalfont-pa-remodeling/"},{"label":"Bucks County","href":"/service-areas/bucks-county/"}],
 "generalPage":"/service-areas/doylestown-new-hope-kitchen-remodeling/","generalPageLabel":"Doylestown & New Hope remodeling overview",
 "distancePhrase":"about 30 minutes from our Maple Glen office via Route 202 or Route 611","permitAuthority":"Doylestown Borough or Doylestown Township, depending on the address, with Historical Architectural Review Board review for exterior changes in the Borough's historic district",
 "housingStock":"Victorian and Federal-era homes in Doylestown Borough's historic district, 1920s–1950s colonials on the Borough's edges, and 1980s–2000s builder colonials across Doylestown Township with builder-grade kitchens and baths.",
 "geo":{"lat":40.3101,"lng":-75.1299},**hero(HEROES[0]),**IMG,"portfolio":pf(8),
 "relatedArticles":{"kitchen":["doylestown-borough-kitchen-remodel-permits-historic","doylestown-historic-homes"],"bathroom":["bucks-county-older-homes","how-to-vet-remodeler-ambler-doylestown"]},
 "verify":["Coordinates 40.3101, -75.1299 (Doylestown Borough) and the 30-minute drive time are from general geographic knowledge, not the repo.","HARB review applies to exterior changes in the Borough historic district; interior kitchen work is typically not reviewed. Confirm current Borough practice."]},
 "content":{"kitchen":{"introH2":"Two Doylestowns, one standard","metaDescription":"Kitchen remodeling in Doylestown, PA by B&B Associates: historic-district Borough homes and Township colonials, permits and HARB handled, itemized estimates.",
  "answerFirst":"B&B Associates remodels kitchens in Doylestown Borough and Doylestown Township, about 30 minutes from our Maple Glen office via Route 202. Kitchens here run $45,000–$150,000+, and the range is wider than most towns because the housing stock is: a Federal-era kitchen off State Street and a 1996 colonial off Route 313 are different projects. We handle Borough and Township permits, coordinate with the Historical Architectural Review Board where it applies, and price every line before work begins.",
  "sections":[{"h2":"The Borough: kitchens in the historic district","paragraphs":["Doylestown Borough's Victorian and Federal-era homes have kitchens that were added, moved or enlarged two or three times over a century, which is why so many of them are a chain of small rooms at the back of the house with a floor that steps down. The remodel usually starts by deciding which of those rooms become the kitchen, and whether the rear wall can open to the yard. Plaster, cast-iron waste lines, a 100-amp panel and joists sistered by a previous owner are normal findings, and we assess for all of them before we quote.","Inside the historic district, interior work is yours to design; exterior changes such as a new rear window or a bumped-out addition go through the Borough's Historical Architectural Review Board, and we prepare that submission as part of the project. Inset cabinetry, unlacquered brass and soapstone or honed marble suit these houses, and we build the sample doors before you decide."]},
   {"h2":"The Township: the 1990s colonial","paragraphs":["Doylestown Township filled in through the 1980s and 1990s with two-story colonials whose kitchens share a layout: oak raised-panel cabinets, a peninsula, a breakfast nook, and a wall between the kitchen and the family room. Almost every Township kitchen we remodel becomes an open plan: peninsula out, wall opened where it is not bearing, one long island with seating, and cabinetry that finally runs to the ceiling.","These houses reward the Premium tier. The mechanicals are modern, the floors are level, and the budget goes into cabinetry, stone and lighting rather than into surprises. Custom or premium semi-custom cabinetry, quartz or quartzite counters, a proper range hood and a layered lighting plan are the four decisions that change the room."]},
   {"h2":"Investment, permits and timing in Doylestown","paragraphs":["Borough historic-home kitchens typically run $75,000–$150,000+ once wiring, plumbing and plaster are brought forward; Township colonial kitchens land $55,000–$110,000 for a full open-concept remodel. Every estimate is itemized, and older-home contingencies are listed as their own lines rather than hidden in a lump sum.","Plan for 12–20 weeks door to door, longer if a HARB submission is part of the scope. Design and selections run 3–8 weeks, permitting 2–4, construction 4–10, and cabinetry is ordered before demolition so lead times do not stall the site."]}],
  "faqOverrides":[{"q":"How much does a kitchen remodel cost in Doylestown, PA?","a":"Kitchen remodels in Doylestown run $45,000–$150,000+. Township colonials with an open-concept redesign typically land $55,000–$110,000; Borough historic homes run $75,000–$150,000+ once plumbing, wiring and plaster are brought forward. Every estimate is itemized line by line before work begins."},{"q":"Do I need Historical Architectural Review Board approval to remodel my Doylestown Borough kitchen?","a":"Interior work is not reviewed. Exterior changes in the Borough's historic district, such as a new rear window, door or addition, go to HARB, and we prepare and present that submission as part of the project. Doylestown Township projects go through the Township building department only."}]},
  "bathroom":{"introH2":"Bathrooms for old bones and new","metaDescription":"Bathroom remodeling in Doylestown, PA by B&B Associates: tile showers, custom vanities, heated floors for Borough historic homes and Township colonials. Permits handled.",
  "answerFirst":"B&B Associates remodels bathrooms in Doylestown Borough and Doylestown Township, about 30 minutes from our Maple Glen office. Bathrooms here run $25,000–$85,000+: hall baths in Township colonials at the lower end, primary suites and historic-home bathrooms with relocated plumbing at the upper end. Our own crews set every tile surface, and we file with the Borough or Township and coordinate every inspection.",
  "sections":[{"h2":"Historic Borough homes: plumbing first, then tile","paragraphs":["A bathroom in a Doylestown Borough Victorian is often the only bathroom the house was built with, wedged into a former closet or hallway with a cast-iron stack and galvanized supply lines behind horsehair plaster. The first job is bringing the plumbing forward; the second is finding the space, which in these houses usually means absorbing an adjacent closet or hall to build a real primary bath.","Once the bones are right, the finish work is what people notice: hex or basketweave mosaic floors, a walk-in shower with a proper linear drain, a furniture-style vanity, and fixtures in unlacquered brass or polished nickel that belong in a house of this age. We waterproof to modern standards behind period-correct surfaces."]},
   {"h2":"Township colonials: the builder bath, rebuilt","paragraphs":["Doylestown Township's 1980s–2000s colonials came with a primary bath the builder priced to a number: a fiberglass tub-shower or a small tiled stall, a cultured-marble double vanity, and a floor that was never heated. The remodel here is the most satisfying one we do. The tub comes out for a large walk-in tile shower with frameless glass, the vanity becomes custom with real storage, and heated floors go in under large-format porcelain.","Because these houses have modern plumbing and framing, the budget goes into what you see and touch. Most Township primary baths land in our Premium tier, and a hall bath refresh in the existing layout sits comfortably in Essential."]},
   {"h2":"Investment, permits and timing in Doylestown","paragraphs":["Hall and guest baths typically run $25,000–$45,000, primary baths in Township colonials $45,000–$75,000, and historic-home or spa-level suites $75,000–$100,000+. Older Borough homes may add cost for cast-iron waste lines, plaster and subfloor repair, listed as their own lines on the estimate.","Most bathrooms are 5–7 weeks of construction after 2–4 weeks of design and 2–4 weeks of permitting through Doylestown Borough or Doylestown Township. Shower glass is measured after tile and arrives about two weeks later, so it is usually the last thing installed."]}],
  "faqOverrides":[{"q":"How much does a bathroom remodel cost in Doylestown, PA?","a":"Bathroom remodels in Doylestown run $25,000–$85,000+. Hall baths generally run $25,000–$45,000, primary baths in Township colonials $45,000–$75,000, and historic Borough homes or spa-level suites $75,000–$100,000+. You receive a fully itemized estimate before any work begins."},{"q":"Do you handle bathroom permits in Doylestown Borough and Doylestown Township?","a":"Yes. We file plumbing, electrical and building permits with Doylestown Borough or Doylestown Township depending on the address, and we coordinate every inspection. Permit management is part of our standard scope, not billed separately."}]}}})

T.append({**{"slug":"new-hope","urlSlug":"new-hope-pa","displayName":"New Hope","county":"Bucks County","regionEyebrow":"Bucks County · Delaware River",
 "townships":["New Hope Borough","Solebury Township"],"neighborhoods":["New Hope Borough","Solebury Township","Lahaska","Carversville","Lumberville"],
 "heroTowns":"New Hope Borough · Solebury · Lahaska · Carversville","neighbors":["doylestown","yardley"],
 "nearbyGeneral":[{"label":"Doylestown & New Hope","href":"/service-areas/doylestown-new-hope-kitchen-remodeling/"},{"label":"Buckingham","href":"/service-areas/buckingham-pa-remodeling/"},{"label":"Bucks County","href":"/service-areas/bucks-county/"}],
 "generalPage":"/service-areas/doylestown-new-hope-kitchen-remodeling/","generalPageLabel":"Doylestown & New Hope remodeling overview",
 "distancePhrase":"about 40 minutes from our Maple Glen office via Route 202","permitAuthority":"New Hope Borough or Solebury Township, depending on the address",
 "housingStock":"18th- and 19th-century stone farmhouses and river-town cottages in New Hope Borough and Solebury, mid-century homes along the canal, and newer estate homes on former farm parcels around Lahaska and Carversville.",
 "geo":{"lat":40.3643,"lng":-74.9513},**hero(HEROES[1]),**IMG,"portfolio":pf(9),
 "relatedArticles":{"kitchen":["bucks-county-older-homes","doylestown-historic-homes"],"bathroom":["bucks-county-older-homes","bathroom-tile-trends-2025"]},
 "verify":["Coordinates 40.3643, -74.9513 (New Hope Borough) and the 40-minute drive time are from general geographic knowledge, not the repo."]},
 "content":{"kitchen":{"introH2":"Stone farmhouses and river cottages","metaDescription":"Kitchen remodeling in New Hope, PA by B&B Associates: stone farmhouse and river-town kitchens in New Hope Borough and Solebury, permits handled, itemized estimates.",
  "answerFirst":"B&B Associates remodels kitchens in New Hope Borough and Solebury Township, about 40 minutes from our Maple Glen office via Route 202. New Hope kitchens run $55,000–$150,000+, higher on average than most of Bucks County because so much of the housing is 18th- and 19th-century stone with kitchens that were never designed for the way the house is used today. We handle Borough and Township permits and price every line before work begins.",
  "sections":[{"h2":"Solebury stone farmhouses","paragraphs":["The classic New Hope project is a stone farmhouse in Solebury whose kitchen sits in a low-ceilinged rear ell added a century after the house was built. The walls are two feet thick, the floor is a step down, and the window openings are the only ones you will get without a mason. The remodel is a study in working with the house: cabinetry scaled to the ceiling height, a range against the old chimney breast, and a layout that makes the ell feel intentional rather than tacked on.","Wiring, plumbing and insulation are usually a generation or two behind, so we open a test area before quoting and list the mechanical work as its own lines. Inset cabinetry in painted or natural white oak, soapstone or honed quartzite, and unlacquered brass suit these houses; we build the sample doors in your kitchen before you decide."]},
   {"h2":"River-town cottages and newer estate homes","paragraphs":["Inside New Hope Borough, the river-town cottages and 1920s–1950s homes near Main Street have small kitchens on tight lots, and the remodel often turns on whether a rear porch or mudroom can be absorbed to gain the length for an island. On the Lahaska and Carversville side, the newer estate homes on former farm parcels have large builder kitchens that want better cabinetry, a proper hood and a lighting plan rather than more square footage.","For both, the decisions that change the room are the same: custom or premium semi-custom cabinetry, stone that suits the light, and appliances placed where the traffic wants them. We coordinate all of it under one contract."]},
   {"h2":"Investment, permits and timing in New Hope","paragraphs":["Stone-farmhouse kitchens typically run $85,000–$150,000+ once mechanicals and masonry are accounted for; cottage and newer-home kitchens land $55,000–$110,000. Every estimate is itemized, and older-home contingencies are separate visible lines.","Plan for 12–20 weeks door to door. New Hope Borough and Solebury Township permitting runs 2–4 weeks; construction 4–10 weeks depending on structural scope. Cabinetry is ordered before demolition so lead times do not stall the site."]}],
  "faqOverrides":[{"q":"How much does a kitchen remodel cost in New Hope, PA?","a":"Kitchen remodels in New Hope and Solebury run $55,000–$150,000+. Stone farmhouses typically land $85,000–$150,000+ once wiring, plumbing and masonry are brought forward; river-town cottages and newer estate homes run $55,000–$110,000. Every estimate is itemized before work begins."},{"q":"Can you remodel a kitchen in an 18th-century stone house without losing its character?","a":"That is most of what we do in Solebury. We keep the stone, the chimney breast and the proportions, bring the mechanicals to code behind the walls, and scale the cabinetry to the ceiling height rather than forcing a modern kitchen into an old room."}]},
  "bathroom":{"introH2":"Bathrooms in houses built before bathrooms","metaDescription":"Bathroom remodeling in New Hope, PA by B&B Associates: primary baths and tile showers for stone farmhouses and river-town homes in New Hope and Solebury. Permits handled.",
  "answerFirst":"B&B Associates remodels bathrooms in New Hope Borough and Solebury Township, about 40 minutes from our Maple Glen office. Bathrooms here run $30,000–$100,000+, because many of these houses were built before indoor plumbing and their bathrooms were fitted into whatever space was left. Our own crews set every tile surface, and we file with the Borough or Township and coordinate every inspection.",
  "sections":[{"h2":"Finding the primary bath in a stone house","paragraphs":["A Solebury farmhouse rarely has a real primary bathroom; it has a bathroom, added in the 1930s, off a hall. Building a proper suite usually means absorbing a small bedroom or a closet, running new supply and waste through stone and old framing, and venting properly for the first time. We plan the plumbing route before anything else, because in a stone house it decides what is possible.","The finish is where these bathrooms come alive: a walk-in shower with a linear drain, marble or zellige tile, a freestanding tub under the old window, radiant heat under a stone floor, and fixtures in nickel or brass. Modern waterproofing sits behind every period-correct surface."]},
   {"h2":"Cottages, canal homes and newer estates","paragraphs":["Borough cottages and canal-side homes have small bathrooms where every inch counts: a curbless shower instead of a tub, a wall-hung vanity, a niche instead of a shelf, and heated floors so a small room feels generous. Newer estate homes around Lahaska come with large builder baths that want a better shower, a custom vanity and real tile in place of the cultured marble.","Both end up in our Premium or Signature tiers depending on how much plumbing moves, and both get an itemized estimate with every line visible before work starts."]},
   {"h2":"Investment, permits and timing in New Hope","paragraphs":["Hall baths run $30,000–$50,000, primary baths $50,000–$85,000, and full suites carved out of a stone house $85,000–$100,000+. Stone-house contingencies are listed as separate lines.","Most bathrooms are 5–7 weeks of construction after design and permitting through New Hope Borough or Solebury Township; suites with new plumbing routes run longer. Custom glass arrives about two weeks after tile is set."]}],
  "faqOverrides":[{"q":"How much does a bathroom remodel cost in New Hope, PA?","a":"Bathroom remodels in New Hope and Solebury run $30,000–$100,000+. Hall baths typically run $30,000–$50,000, primary baths $50,000–$85,000, and full suites built into a stone farmhouse $85,000–$100,000+. Every estimate is itemized before any work begins."},{"q":"Do you handle bathroom permits in New Hope Borough and Solebury Township?","a":"Yes. We file plumbing, electrical and building permits with New Hope Borough or Solebury Township depending on the address and coordinate every inspection as part of our standard scope."}]}}})

T.append({**{"slug":"yardley","urlSlug":"yardley-pa","displayName":"Yardley","county":"Bucks County","regionEyebrow":"Bucks County",
 "townships":["Yardley Borough","Lower Makefield Township"],"neighborhoods":["Yardley Borough","Lower Makefield","Edgewood Village","Makefield Glen","Newtown"],
 "heroTowns":"Yardley Borough · Lower Makefield · Edgewood · Makefield Glen","neighbors":["newtown","langhorne"],
 "nearbyGeneral":[{"label":"Yardley","href":"/service-areas/yardley-pa-remodeling/"},{"label":"Newtown","href":"/service-areas/newtown-pa-kitchen-bathroom-remodeling/"},{"label":"Bucks County","href":"/service-areas/bucks-county/"}],
 "generalPage":"/service-areas/yardley-pa-remodeling/","generalPageLabel":"Yardley remodeling overview",
 "distancePhrase":"about 35 minutes from our Maple Glen office via Route 332 or I-295","permitAuthority":"Yardley Borough or Lower Makefield Township, depending on the address",
 "housingStock":"Victorian and early-1900s homes in Yardley Borough near the canal, and 1970s–1990s colonials and center-hall developments across Lower Makefield with oak kitchens and builder-grade primary baths.",
 "geo":{"lat":40.2457,"lng":-74.8460},**hero(HEROES[2]),**IMG,"portfolio":pf(10),
 "relatedArticles":{"kitchen":["newtown-pa-remodel-before-selling","bucks-county-older-homes"],"bathroom":["yardley-primary-bathroom-closet-conversion","heated-bathroom-floors"]},
 "verify":["Coordinates 40.2457, -74.8460 (Yardley Borough) and the 35-minute drive time are from general geographic knowledge, not the repo."]},
 "content":{"kitchen":{"introH2":"Kitchen design and build in Yardley","metaDescription":"Kitchen design and build in Yardley and Lower Makefield, PA by B&B Associates: open-concept colonial kitchens and Borough Victorians, permits handled, itemized estimates.",
  "answerFirst":"B&B Associates designs and builds kitchens in Yardley Borough and Lower Makefield Township, about 35 minutes from our Maple Glen office. Yardley kitchens run $45,000–$130,000+, and most of them are Lower Makefield colonials from the 1970s–1990s getting the open-concept remodel their layout was always waiting for. We handle Borough and Township permits and price every line before work begins.",
  "sections":[{"h2":"Lower Makefield: the center-hall colonial","paragraphs":["Lower Makefield's developments from the 1970s through the 1990s share a kitchen: a galley or L-shape against the back wall, oak cabinets to a soffit, a peninsula that blocks the family room, and a breakfast area under a bay window. The remodel is almost always the same three moves: the soffit and peninsula come out, the wall to the family room opens where it is not bearing, and one island with seating takes the center of the room.","These houses have modern framing and plumbing, so the budget goes to cabinetry, stone, a real hood and lighting. Painted maple perimeter with a white-oak or walnut island, quartz or quartzite counters, and a layered lighting plan are the four decisions that change the room, and most Lower Makefield kitchens land in our Premium tier."]},
   {"h2":"Yardley Borough: Victorians by the canal","paragraphs":["The Borough's Victorian and early-1900s homes near the canal and Main Street have kitchens at the back of the house that were added or enlarged more than once, with a step-down floor and a mix of plaster and drywall. The first decision is whether the rear wall can open to the yard; the second is where the range goes once the old chimney is accounted for. We open a test area before quoting so wiring, plumbing and joists are known lines, not surprises.","Inset cabinetry, a farmhouse sink under the rear window, honed stone and warm metal suit these houses. We build the sample doors and set them in the kitchen before you decide."]},
   {"h2":"Investment, permits and timing in Yardley","paragraphs":["Lower Makefield colonial kitchens typically run $55,000–$100,000 for a full open-concept remodel; Borough Victorians land $70,000–$130,000+ once mechanicals are brought forward. Every estimate is itemized, and older-home contingencies are their own lines.","Plan for 12–20 weeks door to door. Yardley Borough and Lower Makefield permitting runs 2–4 weeks; construction 4–10 weeks. Cabinetry is ordered before demolition so lead times do not stall the site."]}],
  "faqOverrides":[{"q":"How much does a kitchen remodel cost in Yardley, PA?","a":"Kitchen remodels in Yardley and Lower Makefield run $45,000–$130,000+. A full open-concept remodel of a Lower Makefield colonial typically lands $55,000–$100,000; Borough Victorians run $70,000–$130,000+ once wiring and plumbing are brought forward. Every estimate is itemized before work begins."},{"q":"Do you do cabinet refinishing or refacing in Yardley?","a":"When the cabinet boxes are sound and the layout already works, yes. In most 1970s–1990s Lower Makefield kitchens the layout is the problem, and we will tell you when refacing is money better put toward new cabinetry and an open plan."}]},
  "bathroom":{"introH2":"Primary baths built from closets","metaDescription":"Bathroom remodeling in Yardley and Lower Makefield, PA by B&B Associates: primary bath expansions, tile showers, heated floors, custom vanities. Permits handled.",
  "answerFirst":"B&B Associates remodels bathrooms in Yardley Borough and Lower Makefield Township, about 35 minutes from our Maple Glen office. Yardley bathrooms run $25,000–$85,000+, and the signature project here is the primary bath expansion: the five-by-eight builder bath in a Lower Makefield colonial rebuilt as a real suite by absorbing the closet next door. Our own crews set every tile surface, and we file with the Borough or Township and coordinate every inspection.",
  "sections":[{"h2":"The Lower Makefield primary bath","paragraphs":["Lower Makefield's colonials came with a primary bath the builder squeezed beside a walk-in closet: a fiberglass tub-shower, a small double vanity, and a door that hits the toilet. The remodel we do most often here moves the wall, takes some of the closet, and turns the space into a walk-in tile shower with frameless glass, a freestanding tub where there is room, a custom vanity with real storage and heated floors under large-format porcelain.","Moving plumbing in a second-floor joist bay is routine in these houses, and the framing is modern, so the budget goes into tile, glass, fixtures and cabinetry. Most land in our Premium tier; suites with relocated plumbing and a tub reach Signature."]},
   {"h2":"Borough homes and hall baths","paragraphs":["In Yardley Borough's older homes the challenge is plumbing and space: a cast-iron stack, galvanized supply lines and a bathroom fitted into a former closet. We bring the plumbing forward first, then build a bathroom that suits the age of the house, with mosaic floors, a walk-in shower with a linear drain and a furniture-style vanity.","Hall and guest baths across Yardley usually stay in the existing layout: new tile, a custom vanity, a better shower and lighting, comfortably in our Essential tier and finished in five to six weeks."]},
   {"h2":"Investment, permits and timing in Yardley","paragraphs":["Hall baths run $25,000–$45,000, primary baths $45,000–$75,000, and expanded suites with relocated plumbing $75,000–$100,000+. Older Borough homes may add cost for cast-iron and plaster, listed as separate lines.","Most bathrooms are 5–7 weeks of construction after 2–4 weeks of design and 2–4 weeks of permitting through Yardley Borough or Lower Makefield Township. Shower glass arrives about two weeks after tile is set."]}],
  "faqOverrides":[{"q":"How much does a bathroom remodel cost in Yardley, PA?","a":"Bathroom remodels in Yardley and Lower Makefield run $25,000–$85,000+. Hall baths typically run $25,000–$45,000, primary baths $45,000–$75,000, and expanded suites built by absorbing a closet $75,000–$100,000+. Every estimate is itemized before any work begins."},{"q":"Can you enlarge my Lower Makefield primary bathroom into the closet?","a":"Yes; it is the most common bathroom project we do in Lower Makefield. We move the wall, reroute plumbing in the joist bay, and rebuild the closet smaller and smarter so the suite gains a walk-in shower and often a tub without losing usable storage."}]}}})

T.append({**{"slug":"langhorne","urlSlug":"langhorne-pa","displayName":"Langhorne","county":"Bucks County","regionEyebrow":"Bucks County",
 "townships":["Langhorne Borough","Middletown Township"],"neighborhoods":["Langhorne Borough","Langhorne Manor","Middletown Township","Penndel","Newtown"],
 "heroTowns":"Langhorne Borough · Langhorne Manor · Middletown · Penndel","neighbors":["yardley","newtown"],
 "nearbyGeneral":[{"label":"Newtown","href":"/service-areas/newtown-pa-kitchen-bathroom-remodeling/"},{"label":"Yardley","href":"/service-areas/yardley-pa-remodeling/"},{"label":"Bucks County","href":"/service-areas/bucks-county/"}],
 "generalPage":"/service-areas/bucks-county/","generalPageLabel":"Bucks County remodeling overview",
 "distancePhrase":"about 35 minutes from our Maple Glen office via Route 413 or the Turnpike","permitAuthority":"Langhorne Borough, Langhorne Manor Borough or Middletown Township, depending on the address",
 "housingStock":"Victorian and early-1900s homes in Langhorne Borough, 1950s–1970s ranches, split-levels and Cape Cods across Middletown Township, and 1980s–1990s colonials in the newer Middletown developments.",
 "geo":{"lat":40.1745,"lng":-74.9227},**hero(HEROES[3]),**IMG,"portfolio":pf(11),
 "relatedArticles":{"kitchen":["horsham-warminster-split-level-kitchen-remodel","newtown-pa-remodel-before-selling"],"bathroom":["heated-bathroom-floors","bathroom-remodeling-roi"]},
 "verify":["Coordinates 40.1745, -74.9227 (Langhorne Borough) and the 35-minute drive time are from general geographic knowledge, not the repo.","Langhorne appears in Google Trends city data for 'bathroom remodel' (Philadelphia metro, 5-year); it is the only lower-Bucks town that does."]},
 "content":{"kitchen":{"introH2":"Ranches, splits and Borough Victorians","metaDescription":"Kitchen remodeling in Langhorne and Middletown Township, PA by B&B Associates: split-level and ranch kitchens opened up, Borough Victorians restored, permits handled.",
  "answerFirst":"B&B Associates remodels kitchens in Langhorne Borough, Langhorne Manor and Middletown Township, about 35 minutes from our Maple Glen office via Route 413. Langhorne kitchens run $45,000–$120,000+, and most of them are mid-century ranches and split-levels whose small, closed kitchens want to open to the living room. We handle Borough and Township permits and price every line before work begins.",
  "sections":[{"h2":"Middletown ranches and split-levels","paragraphs":["Middletown Township built out in the 1950s–1970s with ranches, Cape Cods and split-levels, and their kitchens are small, closed rooms with a single window, a wall to the living room and cabinets that stop at a soffit. The remodel that changes these houses is structural: the wall comes down or becomes a wide cased opening with a beam, the kitchen gains a peninsula or a compact island, and cabinetry runs to the ceiling for the first time.","Split-levels add the half-flight problem: the kitchen sits a few steps above the family room, and the design has to make the two levels read as one space. We have done enough of these in Bucks and eastern Montgomery County to know where the beam goes and what the electrical panel will need."]},
   {"h2":"Borough Victorians and 1980s colonials","paragraphs":["Langhorne Borough's Victorian and early-1900s homes have rear kitchens that were enlarged a century ago with a step-down floor, plaster walls and plumbing that predates the appliances. We open a test area before quoting so wiring, waste lines and joists are known lines, and we design cabinetry, inset or overlay, to the proportions of the house.","The 1980s–1990s colonials in Middletown's newer developments are the straightforward projects: oak cabinets and a peninsula out, an island in, a wall to the family room opened where it is not bearing, and the budget spent on cabinetry, stone, a real hood and lighting."]},
   {"h2":"Investment, permits and timing in Langhorne","paragraphs":["Ranch and split-level kitchens with a wall removed typically run $55,000–$95,000; colonial open-concept remodels $55,000–$100,000; Borough Victorians $65,000–$120,000+ once mechanicals are brought forward. Every estimate is itemized, and structural and older-home lines are visible, not lumped.","Plan for 12–20 weeks door to door. Langhorne Borough, Langhorne Manor and Middletown Township permitting runs 2–4 weeks; construction 4–10 weeks. Cabinetry is ordered before demolition."]}],
  "faqOverrides":[{"q":"How much does a kitchen remodel cost in Langhorne, PA?","a":"Kitchen remodels in Langhorne and Middletown Township run $45,000–$120,000+. Ranch and split-level kitchens with a wall opened typically land $55,000–$95,000; Borough Victorians run $65,000–$120,000+ once wiring and plumbing are brought forward. Every estimate is itemized before work begins."},{"q":"Can you open the wall between my split-level kitchen and living room?","a":"Usually, yes. Most Middletown split-level and ranch kitchen walls are bearing, so the opening gets a properly sized beam and posts, permitted through the Township. We design the two levels to read as one space and handle the structural engineering as part of the project."}]},
  "bathroom":{"introH2":"Bathrooms for mid-century and Victorian Langhorne","metaDescription":"Bathroom remodeling in Langhorne and Middletown Township, PA by B&B Associates: tile showers, tub-to-shower conversions, custom vanities, heated floors. Permits handled.",
  "answerFirst":"B&B Associates remodels bathrooms in Langhorne Borough, Langhorne Manor and Middletown Township, about 35 minutes from our Maple Glen office. Langhorne bathrooms run $22,000–$80,000+, and the most requested project is the tub-to-shower conversion in a 1960s ranch or split-level hall bath, followed by primary-bath expansions in the newer colonials. Our own crews set every tile surface, and we file with the Borough or Township and coordinate every inspection.",
  "sections":[{"h2":"The mid-century hall bath, rebuilt","paragraphs":["Middletown's ranches and split-levels have a five-by-eight hall bath with a cast-iron tub, 4x4 tile to chair-rail height, and a single vanity. The remodel that changes daily life is a tub-to-shower conversion: the tub out, a tiled walk-in shower with a linear drain and frameless glass in, a vanity with real storage, better lighting and a proper exhaust fan. Kept in the existing footprint it sits in our Essential or Premium tier and takes five to six weeks.","Because plumbing in these houses is often original galvanized and cast iron, we bring supply and waste forward while the walls are open and list it as its own line."]},
   {"h2":"Primary baths and Borough Victorians","paragraphs":["The 1980s–1990s Middletown colonials came with a builder primary bath: fiberglass tub-shower, cultured-marble double vanity, no heated floor. The remodel is a large walk-in tile shower, a custom vanity, heated floors under large-format porcelain, and frameless glass; when there is a closet beside it, the suite can grow.","Langhorne Borough Victorians follow the same first rule as every historic home we work in: plumbing first, then space, then finish. Mosaic floors, a walk-in shower with a linear drain, and a furniture-style vanity suit these houses, with modern waterproofing behind every period surface."]},
   {"h2":"Investment, permits and timing in Langhorne","paragraphs":["Hall baths and tub-to-shower conversions run $22,000–$45,000, primary baths $45,000–$70,000, and expanded suites or Victorian rebuilds $70,000–$80,000+. Older-home plumbing is a separate, visible line on the estimate.","Most bathrooms are 5–7 weeks of construction after 2–4 weeks of design and 2–4 weeks of permitting through Langhorne Borough, Langhorne Manor or Middletown Township. Shower glass arrives about two weeks after tile is set."]}],
  "faqOverrides":[{"q":"How much does a bathroom remodel cost in Langhorne, PA?","a":"Bathroom remodels in Langhorne and Middletown Township run $22,000–$80,000+. Tub-to-shower conversions and hall baths typically run $22,000–$45,000, primary baths $45,000–$70,000, and expanded suites $70,000–$80,000+. Every estimate is itemized before any work begins."},{"q":"How much does a tub-to-shower conversion cost in Langhorne?","a":"In the existing footprint, a tiled walk-in shower with frameless glass replacing a hall-bath tub typically lands in our Essential to Premium range, $22,000–$45,000 depending on tile, glass and whether the drain moves. We price it line by line after seeing the space."}]}}})

T.append({**{"slug":"horsham","urlSlug":"horsham-pa","displayName":"Horsham","county":"Montgomery County","regionEyebrow":"Montgomery County",
 "townships":["Horsham Township"],"neighborhoods":["Horsham Township","Horsham Village","Maple Glen","Hatboro","Willow Grove"],
 "heroTowns":"Horsham Township · Horsham Village · Hatboro · Willow Grove","neighbors":["ambler","lower-gwynedd","warrington"],
 "nearbyGeneral":[{"label":"Horsham","href":"/service-areas/horsham-pa-remodeling/"},{"label":"Ambler","href":"/service-areas/ambler-pa-remodeling-contractor/"},{"label":"Warminster","href":"/service-areas/warminster-pa-remodeling/"},{"label":"Montgomery County","href":"/service-areas/montgomery-county/"}],
 "generalPage":"/service-areas/horsham-pa-remodeling/","generalPageLabel":"Horsham remodeling overview",
 "distancePhrase":"about 15 minutes from our office at 1141 E Welsh Rd in Maple Glen","permitAuthority":"Horsham Township",
 "housingStock":"1960s–1980s split-levels, ranches and bi-levels across Horsham Township, 1990s–2000s colonials in the newer developments toward Maple Glen, and a handful of older farmhouses along Horsham Road and Welsh Road.",
 "geo":{"lat":40.1784,"lng":-75.1285},**hero(HEROES[0]),**IMG,"portfolio":pf(12),
 "relatedArticles":{"kitchen":["horsham-warminster-split-level-kitchen-remodel","ambler-fort-washington-old-house-kitchen-wiring-plaster"],"bathroom":["fort-washington-bathroom-mold-ventilation-remodel","heated-bathroom-floors"]},
 "verify":["Coordinates 40.1784, -75.1285 (Horsham Township) are from general geographic knowledge, not the repo. The 15-minute drive time matches the existing Horsham page."]},
 "content":{"kitchen":{"introH2":"The split-level kitchen problem","metaDescription":"Kitchen remodeling in Horsham, PA by B&B Associates, 15 minutes from our office: split-level and ranch kitchens opened up, colonial kitchens rebuilt, permits handled.",
  "answerFirst":"B&B Associates remodels kitchens across Horsham Township, about 15 minutes from our office in Maple Glen, which makes Horsham one of the towns we are in most weeks. Horsham kitchens run $45,000–$120,000+, and the defining project is the 1960s–1980s split-level or ranch kitchen: a small closed room a half-flight above the family room that wants to open up. We handle Horsham Township permits and price every line before work begins.",
  "sections":[{"h2":"Splits, bi-levels and ranches","paragraphs":["Horsham built out in the 1960s through the 1980s, and most of its kitchens are closed rooms with one window, a wall to the living room, and cabinets stopping at a soffit. The remodel that changes these houses is structural: the wall becomes a wide cased opening with a properly sized beam, the kitchen gains a peninsula or compact island, and cabinetry finally runs to the ceiling. In a split-level, the design also has to make the half-flight between kitchen and family room read as one space.","We have done enough of these across Horsham, Warminster and Hatboro to know where the beam goes, what the 100-amp panel will need, and how to keep the project in the Premium tier by leaving plumbing where it is."]},
   {"h2":"Colonials toward Maple Glen and older farmhouses","paragraphs":["The 1990s–2000s colonials on the Maple Glen side of the Township have large builder kitchens with oak or maple cabinets, a peninsula and a breakfast room; the remodel is the open-concept redesign with one island, cabinetry to the ceiling, quartz or quartzite and a real lighting plan, and the budget goes to finishes because the mechanicals are modern.","The older farmhouses along Horsham and Welsh Roads are the exception: plaster, cast iron, low rear ells. We open a test area before quoting and design cabinetry to the proportions of the house."]},
   {"h2":"Investment, permits and timing in Horsham","paragraphs":["Split-level and ranch kitchens with a wall opened typically run $55,000–$95,000; colonial open-concept remodels $55,000–$100,000; farmhouse kitchens $65,000–$120,000+. Every estimate is itemized, with structural and older-home lines visible.","Plan for 12–20 weeks door to door. Horsham Township permitting runs 2–4 weeks; construction 4–10 weeks. Being 15 minutes away means our crew and our project manager are on site daily."]}],
  "faqOverrides":[{"q":"How much does a kitchen remodel cost in Horsham, PA?","a":"Kitchen remodels in Horsham run $45,000–$120,000+. Split-level and ranch kitchens with the wall opened typically land $55,000–$95,000; colonial open-concept remodels $55,000–$100,000; older farmhouses $65,000–$120,000+. Every estimate is itemized before work begins."},{"q":"How far is B&B Associates from Horsham?","a":"About 15 minutes. Our office and warehouse are at 1141 E Welsh Rd in Maple Glen, on the Upper Dublin side of the Horsham line, so Horsham projects get daily visits from our project manager and short lead times for material pickups."}]},
  "bathroom":{"introH2":"Bathrooms 15 minutes from our door","metaDescription":"Bathroom remodeling in Horsham, PA by B&B Associates, 15 minutes from our office: tub-to-shower conversions, tile showers, custom vanities, heated floors. Permits handled.",
  "answerFirst":"B&B Associates remodels bathrooms across Horsham Township, about 15 minutes from our office in Maple Glen. Horsham bathrooms run $22,000–$80,000+, and the two projects we do most are the tub-to-shower conversion in a 1960s–1980s hall bath and the primary-bath rebuild in a 1990s colonial. Our own crews set every tile surface, and we file with Horsham Township and coordinate every inspection.",
  "sections":[{"h2":"The hall bath in a split or ranch","paragraphs":["Horsham's split-levels, bi-levels and ranches have a five-by-eight hall bath with a cast-iron tub, tile to chair-rail height and a single vanity, and they are often the only full bath upstairs. The tub-to-shower conversion is the remodel that changes daily life: a tiled walk-in shower with a linear drain and frameless glass, a vanity with real storage, proper exhaust and lighting, kept in the existing footprint and finished in five to six weeks.","Original galvanized supply lines and cast-iron waste are common, so we bring the plumbing forward while the walls are open and list it as its own line. Ventilation is the other recurring fix; a bathroom that has been damp for forty years gets a real fan, not a louder one."]},
   {"h2":"Primary baths in the colonials","paragraphs":["The 1990s–2000s colonials toward Maple Glen came with a builder primary bath: fiberglass tub-shower or a small stall, cultured-marble double vanity, no heated floor. The rebuild is a large walk-in tile shower with frameless glass, a custom vanity, heated floors under large-format porcelain, and often a freestanding tub where the old one was. Modern framing and plumbing mean the budget goes to what you see.","Most Horsham primary baths land in our Premium tier; suites that absorb a closet or move plumbing reach Signature."]},
   {"h2":"Investment, permits and timing in Horsham","paragraphs":["Hall baths and tub-to-shower conversions run $22,000–$45,000, primary baths $45,000–$70,000, and expanded suites $70,000–$80,000+. Older-home plumbing and ventilation are separate visible lines.","Most bathrooms are 5–7 weeks of construction after 2–4 weeks of design and 2–4 weeks of permitting through Horsham Township. Shower glass arrives about two weeks after tile is set."]}],
  "faqOverrides":[{"q":"How much does a bathroom remodel cost in Horsham, PA?","a":"Bathroom remodels in Horsham run $22,000–$80,000+. Tub-to-shower conversions and hall baths typically run $22,000–$45,000, primary baths $45,000–$70,000, and expanded suites $70,000–$80,000+. Every estimate is itemized before any work begins."},{"q":"Do you handle bathroom permits in Horsham Township?","a":"Yes. We file plumbing, electrical and building permits with Horsham Township and coordinate every inspection as part of our standard scope. Being 15 minutes away, inspections rarely hold up a Horsham schedule."}]}}})

T.append({**{"slug":"warrington","urlSlug":"warrington-pa","displayName":"Warrington","county":"Bucks County","regionEyebrow":"Bucks County",
 "townships":["Warrington Township"],"neighborhoods":["Warrington Township","Eureka","Neshaminy","Chalfont","Doylestown"],
 "heroTowns":"Warrington Township · Eureka · Neshaminy · Route 611 corridor","neighbors":["chalfont","doylestown","horsham"],
 "nearbyGeneral":[{"label":"Warrington","href":"/service-areas/warrington-pa-remodeling/"},{"label":"Chalfont","href":"/service-areas/chalfont-pa-remodeling/"},{"label":"Warminster","href":"/service-areas/warminster-pa-remodeling/"},{"label":"Bucks County","href":"/service-areas/bucks-county/"}],
 "generalPage":"/service-areas/warrington-pa-remodeling/","generalPageLabel":"Warrington remodeling overview",
 "distancePhrase":"about 20 minutes from our Maple Glen office via Route 611 or Limekiln Pike","permitAuthority":"Warrington Township",
 "housingStock":"1990s–2010s colonials and townhome developments across Warrington Township, 1960s–1970s ranches and splits near Route 611, and older farmhouses on the remaining agricultural parcels.",
 "geo":{"lat":40.2492,"lng":-75.1349},**hero(HEROES[1]),**IMG,"portfolio":pf(13),
 "relatedArticles":{"kitchen":["custom-vs-semi-custom-cabinetry","horsham-warminster-split-level-kitchen-remodel"],"bathroom":["heated-bathroom-floors","main-line-bathroom-trends"]},
 "verify":["Coordinates 40.2492, -75.1349 (Warrington Township) and the 20-minute drive time are from general geographic knowledge, not the repo."]},
 "content":{"kitchen":{"introH2":"Luxury kitchens for Warrington's newer homes","metaDescription":"Luxury kitchen remodeling in Warrington, PA by B&B Associates, 20 minutes from our office: colonial and townhome kitchens rebuilt with custom cabinetry, permits handled.",
  "answerFirst":"B&B Associates remodels kitchens across Warrington Township, about 20 minutes from our Maple Glen office via Route 611. Warrington kitchens run $45,000–$110,000+, and most of them are 1990s–2010s colonials and townhomes whose builder kitchens have good bones and forgettable finishes. The remodel here is about cabinetry, stone and light rather than structure. We handle Warrington Township permits and price every line before work begins.",
  "sections":[{"h2":"The builder kitchen, done properly","paragraphs":["Warrington's developments from the 1990s through the 2010s share a kitchen the builder priced to a number: maple or oak cabinets to a soffit, laminate or early granite, a peninsula or a small island, and can lights on one switch. The layout is often close to right; what changes the room is custom or premium semi-custom cabinetry to the ceiling, a longer island with seating, quartz or quartzite, a real range hood and a lighting plan with layers.","Because the framing, plumbing and electrical are modern, Warrington kitchens are the cleanest Premium-tier projects we do: the budget goes to what you see and touch, and the schedule holds."]},
   {"h2":"Townhomes, ranches and the farmhouses that remain","paragraphs":["Townhome kitchens in Warrington are narrow and open to the living area already; the remodel is about storage and scale, with a galley of full-height cabinetry, a compact island or peninsula with seating, and lighting that makes a long room feel intentional. The 1960s–1970s ranches and splits near Route 611 follow the open-the-wall playbook we use across Horsham and Warminster.","The farmhouses on the Township's remaining agricultural parcels are the exception and the most rewarding: low rear ells, plaster, cast iron, and a chimney breast that becomes the anchor for the range. We open a test area before quoting."]},
   {"h2":"Investment, permits and timing in Warrington","paragraphs":["Colonial and townhome kitchens typically run $45,000–$95,000; ranch and split kitchens with a wall opened $55,000–$95,000; farmhouses $65,000–$110,000+. Every estimate is itemized before work begins.","Plan for 12–20 weeks door to door. Warrington Township permitting runs 2–4 weeks; construction 4–10 weeks. Cabinetry is ordered before demolition so lead times do not stall the site."]}],
  "faqOverrides":[{"q":"How much does a kitchen remodel cost in Warrington, PA?","a":"Kitchen remodels in Warrington run $45,000–$110,000+. Colonial and townhome kitchens typically land $45,000–$95,000 for new cabinetry, stone, island and lighting; ranches and splits with a wall opened $55,000–$95,000; older farmhouses $65,000–$110,000+. Every estimate is itemized before work begins."},{"q":"Is it worth remodeling a 2000s builder kitchen in Warrington?","a":"Usually, yes. The framing, plumbing and electrical are modern, so the money goes to cabinetry, stone, a real hood and lighting rather than to surprises. That is why Warrington kitchens are among the most predictable Premium-tier projects we do."}]},
  "bathroom":{"introH2":"Bathrooms with strong tile reviews","metaDescription":"Bathroom remodeling in Warrington, PA by B&B Associates, 20 minutes from our office: walk-in tile showers, custom vanities, heated floors for colonials and townhomes. Permits handled.",
  "answerFirst":"B&B Associates remodels bathrooms across Warrington Township, about 20 minutes from our Maple Glen office. Warrington bathrooms run $22,000–$75,000+, and the most common project is the primary-bath rebuild in a 1990s–2010s colonial: fiberglass out, a walk-in tile shower, custom vanity and heated floors in. Our own crews set every tile surface, and we file with Warrington Township and coordinate every inspection.",
  "sections":[{"h2":"The colonial primary bath","paragraphs":["Warrington's colonials came with a primary bath sized generously but finished to a builder's number: a fiberglass tub-shower or a small tiled stall, a cultured-marble double vanity, a soffit over the shower and no heated floor. The rebuild uses the room that is already there: a large walk-in tile shower with a linear drain and frameless glass, a custom vanity with real storage, heated floors under large-format porcelain, and a freestanding tub where the old one stood.","Modern framing and plumbing keep these in our Premium tier, and the tile is where the budget shows: large-format porcelain, natural stone accents, a custom niche and bench, all set by our own crews."]},
   {"h2":"Townhome and hall baths","paragraphs":["Townhome and hall baths in Warrington stay in the existing footprint: a tub-to-shower conversion where the household has outgrown the tub, new tile, a custom vanity, better lighting and a real exhaust fan, comfortably in our Essential tier and finished in five to six weeks.","The 1960s–1970s ranches near Route 611 add the usual mid-century line items, galvanized supply and cast iron, which we bring forward while the walls are open and list separately."]},
   {"h2":"Investment, permits and timing in Warrington","paragraphs":["Hall baths and tub-to-shower conversions run $22,000–$42,000, primary baths $42,000–$70,000, and suites with relocated plumbing $70,000–$75,000+. Every estimate is itemized before any work begins.","Most bathrooms are 5–7 weeks of construction after 2–4 weeks of design and 2–4 weeks of permitting through Warrington Township. Shower glass arrives about two weeks after tile is set."]}],
  "faqOverrides":[{"q":"How much does a bathroom remodel cost in Warrington, PA?","a":"Bathroom remodels in Warrington run $22,000–$75,000+. Hall baths and tub-to-shower conversions typically run $22,000–$42,000, primary baths in colonials $42,000–$70,000, and suites with relocated plumbing $70,000–$75,000+. Every estimate is itemized before any work begins."},{"q":"Do you handle bathroom permits in Warrington Township?","a":"Yes. We file plumbing, electrical and building permits with Warrington Township and coordinate every inspection as part of our standard scope, not billed separately."}]}}})

T.append({**{"slug":"chalfont","urlSlug":"chalfont-pa","displayName":"Chalfont","county":"Bucks County","regionEyebrow":"Bucks County",
 "townships":["Chalfont Borough","New Britain Township"],"neighborhoods":["Chalfont Borough","New Britain Township","New Britain Borough","Colmar","Doylestown"],
 "heroTowns":"Chalfont Borough · New Britain · Colmar · Butler Avenue","neighbors":["doylestown","warrington","lower-gwynedd"],
 "nearbyGeneral":[{"label":"Chalfont","href":"/service-areas/chalfont-pa-remodeling/"},{"label":"Doylestown & New Hope","href":"/service-areas/doylestown-new-hope-kitchen-remodeling/"},{"label":"Lansdale","href":"/service-areas/lansdale-pa-remodeling/"},{"label":"Bucks County","href":"/service-areas/bucks-county/"}],
 "generalPage":"/service-areas/chalfont-pa-remodeling/","generalPageLabel":"Chalfont remodeling overview",
 "distancePhrase":"about 20 minutes from our Maple Glen office via Route 202 or Limekiln Pike","permitAuthority":"Chalfont Borough, New Britain Borough or New Britain Township, depending on the address",
 "housingStock":"Victorian and early-1900s homes along Butler Avenue in Chalfont Borough, 1950s–1970s ranches and splits in New Britain, and 1990s–2000s colonials in the newer New Britain Township developments.",
 "geo":{"lat":40.2884,"lng":-75.2091},**hero(HEROES[2]),**IMG,"portfolio":pf(14),
 "relatedArticles":{"kitchen":["custom-cabinetry-montgomery-county","bucks-county-older-homes"],"bathroom":["heated-bathroom-floors","bathroom-tile-trends-2025"]},
 "verify":["Coordinates 40.2884, -75.2091 (Chalfont Borough) and the 20-minute drive time are from general geographic knowledge, not the repo."]},
 "content":{"kitchen":{"introH2":"Custom cabinets for Chalfont kitchens","metaDescription":"Kitchen remodeling in Chalfont and New Britain, PA by B&B Associates, 20 minutes from our office: custom cabinetry, countertops, open-concept redesigns. Permits handled.",
  "answerFirst":"B&B Associates remodels kitchens in Chalfont Borough, New Britain Borough and New Britain Township, about 20 minutes from our Maple Glen office via Route 202. Chalfont kitchens run $45,000–$115,000+, and the questions we get from Chalfont homeowners are about cabinetry and countertops more than anything else, so that is where this page starts. We handle Borough and Township permits and price every line before work begins.",
  "sections":[{"h2":"Cabinetry and countertops, chosen in your kitchen","paragraphs":["Chalfont and New Britain kitchens span Victorians on Butler Avenue, 1960s ranches, and 2000s colonials, and the cabinetry decision is different in each. Inset painted maple suits the Borough's older homes; full-overlay shaker in painted maple with a white-oak or walnut island carries the colonials; slab doors in rift white oak give a ranch a modern kitchen it never had. Through 60+ supplier partners we bring cabinetry and stone in at trade pricing, and we set sample doors and stone samples in your kitchen before you decide.","Premium semi-custom covers most Chalfont kitchens beautifully at 30–50% less than full custom; we say so plainly when that is the right call, and we say when only custom will do."]},
   {"h2":"Ranches, colonials and Butler Avenue","paragraphs":["New Britain's 1950s–1970s ranches and splits have small closed kitchens that want the wall to the living room opened with a properly sized beam and cabinetry to the ceiling. The 1990s–2000s colonials in the Township's newer developments get the open-concept redesign: peninsula out, island in, wall opened where it is not bearing, budget to cabinetry, stone and lighting.","Butler Avenue's Victorians have rear kitchens with step-down floors, plaster and plumbing older than the appliances. We open a test area before quoting and design cabinetry to the proportions of the house."]},
   {"h2":"Investment, permits and timing in Chalfont","paragraphs":["Colonial open-concept kitchens typically run $55,000–$100,000; ranch and split kitchens with a wall opened $55,000–$95,000; Borough Victorians $65,000–$115,000+ once mechanicals are brought forward. Every estimate is itemized with cabinetry, stone and structural lines visible.","Plan for 12–20 weeks door to door. Chalfont Borough, New Britain Borough and New Britain Township permitting runs 2–4 weeks; construction 4–10 weeks. Cabinetry is ordered before demolition."]}],
  "faqOverrides":[{"q":"How much does a kitchen remodel cost in Chalfont, PA?","a":"Kitchen remodels in Chalfont and New Britain run $45,000–$115,000+. Colonial open-concept remodels typically land $55,000–$100,000; ranches and splits with a wall opened $55,000–$95,000; Borough Victorians $65,000–$115,000+ once wiring and plumbing are brought forward. Every estimate is itemized before work begins."},{"q":"Do you install custom cabinets and countertops in Chalfont?","a":"Yes. Custom and premium semi-custom cabinetry plus quartz, quartzite, marble and soapstone countertops come through our 60+ supplier partners at trade pricing, templated, fabricated and installed by our team as part of a full kitchen remodel."}]},
  "bathroom":{"introH2":"Bathroom cabinetry, tile and heated floors","metaDescription":"Bathroom remodeling in Chalfont and New Britain, PA by B&B Associates, 20 minutes from our office: custom vanities, tile showers, heated floors. Permits handled.",
  "answerFirst":"B&B Associates remodels bathrooms in Chalfont Borough, New Britain Borough and New Britain Township, about 20 minutes from our Maple Glen office. Chalfont bathrooms run $22,000–$75,000+, and the most requested items are custom bathroom cabinetry, walk-in tile showers and heated floors. Our own crews set every tile surface, and we file with the Borough or Township and coordinate every inspection.",
  "sections":[{"h2":"Custom vanities sized to the wall","paragraphs":["Chalfont homeowners ask about bathroom cabinetry more than most towns, and it is the right question: a vanity sized to the wall rather than to the nearest stock width, with drawers instead of doors and a linen tower where there is room, is usually the difference between a bathroom that looks renovated and one that looks designed. We build custom and premium semi-custom vanities in the same finishes as our kitchens, so a house reads as one project.","Paired with a walk-in tile shower, frameless glass and heated floors under large-format porcelain, a primary bath in a New Britain colonial lands in our Premium tier."]},
   {"h2":"Hall baths, ranches and Victorians","paragraphs":["Hall baths across Chalfont stay in the existing footprint: a tub-to-shower conversion where the household has outgrown the tub, new tile, a custom vanity, proper lighting and exhaust, in our Essential tier and done in five to six weeks. The 1950s–1970s ranches add galvanized supply and cast-iron waste, brought forward while the walls are open and listed separately.","Butler Avenue Victorians follow our historic-home rule: plumbing first, then space, then finish, with mosaic floors and a furniture-style vanity over modern waterproofing."]},
   {"h2":"Investment, permits and timing in Chalfont","paragraphs":["Hall baths and tub-to-shower conversions run $22,000–$42,000, primary baths $42,000–$70,000, and expanded suites or Victorian rebuilds $70,000–$75,000+. Every estimate is itemized before any work begins.","Most bathrooms are 5–7 weeks of construction after 2–4 weeks of design and 2–4 weeks of permitting through Chalfont Borough, New Britain Borough or New Britain Township. Shower glass arrives about two weeks after tile is set."]}],
  "faqOverrides":[{"q":"How much does a bathroom remodel cost in Chalfont, PA?","a":"Bathroom remodels in Chalfont and New Britain run $22,000–$75,000+. Hall baths and tub-to-shower conversions typically run $22,000–$42,000, primary baths $42,000–$70,000, and expanded suites $70,000–$75,000+. Every estimate is itemized before any work begins."},{"q":"Do you build custom bathroom cabinetry in Chalfont?","a":"Yes. Custom vanities, linen towers and medicine cabinets are part of every B&B bathroom remodel, sized to the wall and finished to match the rest of the house, sourced through our 60+ supplier partners at trade pricing."}]}}})

added = []
for t in T:
    if t['slug'] in have: continue
    for k in ('kitchen', 'bathroom'):
        n = len(t['content'][k]['metaDescription'])
        if not 120 <= n <= 165: print(f"  meta length {n}: {t['slug']} {k}")
    d['towns'].append(t); added.append(t['slug'])
nt = [x for x in d['towns'] if x['slug'] == 'newtown'][0]; nt['neighbors'] = ['yardley', 'langhorne']
p.write_text(json.dumps(d, indent=2, ensure_ascii=False) + "\n")
print(len(d['towns']), "towns; added", added)
